language: python

python:
- 3.6
- 3.7

services:
- mysql

branches:
  only:
  - develop

services:
  - mysql

addons:
  apt_packages:
     - libcups2-dev

install:
  - pip3 install --upgrade pip setuptools
  - pip3 install flake8
  - pip3 install coveralls
  - pip install -e .
  - pip3 install -q -r requirements.txt

before_script:
  - flake8 edc_visit_tracking
  - mysql -e 'create database edc character set utf8;'

script: 
  - coverage run --source=edc_visit_tracking manage.py test

after_success:
  - coveralls
