# Generated by Django 4.2.5 on 2023-09-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "edc_visit_tracking",
            "0006_alter_historicalsubjectvisit_device_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectvisitmissed",
            name="subject_visit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_visit_tracking.subjectvisit",
            ),
        ),
        migrations.AlterField(
            model_name="subjectvisitmissed",
            name="subject_visit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="edc_subject_visit",
                to="edc_visit_tracking.subjectvisit",
            ),
        ),
    ]
